# generated by stubbs:add-option
# Sat  8 Sep 2012 20:23:23 EDT

# print USAGE and exit
rerun_option_error() {
    [ -z "$USAGE"  ] && echo "$USAGE" >&2
    [ -z "$SYNTAX" ] && echo "$SYNTAX $*" >&2
    return 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_error
}

# options: [acapi-pass acapi-user project revision repo]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        --acapi-pass) rerun_option_check $# ; ACAPI_PASS=$2 ; shift ;;
        --acapi-user) rerun_option_check $# ; ACAPI_USER=$2 ; shift ;;
        -p|--project) rerun_option_check $# ; PROJECT=$2 ; shift ;;
        -r|--repo) rerun_option_check $# ; REPO=$2 ; shift ;;
        # unknown option
        -?)
            rerun_option_error
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$PROJECT" ] && PROJECT=secondlevel

# Check required options are set
[ -z "$ACAPI_USER" ] && { echo "missing required option: --acapi-user" ; return 2 ; }
[ -z "$ACAPI_PASS" ] && { echo "missing required option: --acapi-pass" ; return 2 ; }
[ -z "$REPO" ] && { echo "missing required option: --repo" ; return 2 ; }
#
return 0
