# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue  5 Feb 2013 11:09:45 EST
#
#/ usage: renamer:rename [ --from <skeletor>]  --to <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --from) rerun_option_check $# $1; FROM=$2 ; shift ;;
            --to) rerun_option_check $# $1; TO=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$FROM" ] && FROM="$(rerun_property_get $RERUN_MODULE_DIR/options/from DEFAULT)"
    # Check required options are set
    # If option variables are declared exportable, export them.
    export FROM
    export TO
    #
    return 0
}


# Initialize the options variables to null.
FROM=
TO=


