#!/usr/bin/env bash

# To implement this command, edit the "Command implementation" section below. 

# Usage
# -----

# Comments prefixed with `#/` are managed by stubbs.
# The `command` and `usage` comments describe the command
# and show its options.
# 
#/ command: renamer:rename: "A command to rename the project"
#/ usage: rerun renamer:rename [ --from <skeletor>]  --to <> 

# Load common functions
# ---------------------

# Load the function library for this module.
# This loads rerun functions, too.
. $RERUN_MODULE_DIR/lib/functions.sh rename || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------

# This script is designed to _fail-fast_.

# Trap errors and exit. The call to `rerun_die` will print the
# the error message and exit with the error command exit status. 

trap 'rerun_die $? "*** command failed: renamer:rename. ***"' ERR

# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
# so a pipeline return status is the value of the last 
# (rightmost) command to exit with non-zero status.
#
# [set]: http://ss64.com/bash/set.html
# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html

set -o nounset -o pipefail

# Command variables
# -----------------

# This command script can access the following variables
# declared by `rerun` or by the option parser function.

#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: FROM TO

# The `rerun_options_parse` function processes the command line
# arguments. Each accepted command line flag results in setting 
# one the corresponding option variables.

rerun_options_parse "$@"


# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

GITHUB_ORG=myplanetdigital
REGEX_FIND="$GITHUB_ORG/(drupal-)?$FROM"
sed -Ei '' "s#$REGEX_FIND#$REPO#" build-*.make

# Remove Skeletor-specific instructions.
rm -f SKELETOR-README.md

# Search and replace within every file where $FROM string found.
for file in `grep -il "$FROM" *.*`
do
  perl -pe "s/$FROM/$TO/gi" -i $file
done

# Rename all files with $FROM filename pattern.
REGEX_FIND="\(.*\)${FROM}\(.*\)"
REGEX_REPLACE="mv & \1${TO}\2"
find . -name "*${FROM}*" | sed "s/$REGEX_FIND/$REGEX_REPLACE/" | bash

# Done. Exit with last command exit status.
exit $?

